version: "3.9"

services:
  db:
    image: postgres:16
    container_name: ims_db
    restart: always
    env_file:
      - .env # Use .env file to load environment variables for the backend service
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  license-server:
    build: ./license-server
    container_name: ims-license-server
    restart: always
    ports:
      - "5050:5000"
    volumes:
      - license-server_license_data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://license-server:5000/health"]
      interval: 10s
      timeout: 3s
      retries: 10

  backend:
    build: ./backend
    container_name: ims_backend
    hostname: ims-backend-prod
    restart: always
    environment:
      RUNNING_IN_DOCKER: "1"
    env_file:
      - .env  # Use .env file to load environment variables for the backend service
    depends_on:
      db:
        condition: service_started
      license-server:
        condition: service_healthy
    volumes:
      - ./backend/staticfiles:/app/staticfiles
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: ims_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

  backup:
    image: postgres:16-alpine
    container_name: ims_backup
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Kolkata
    volumes:
      - ./backups:/backups
      - ./backup/backup.sh:/backup.sh
      - ./backup/crontabs:/etc/crontabs
    entrypoint: /bin/sh
    command: -c "apk add --no-cache postgresql-client tzdata && cp /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && echo 'Asia/Kolkata' > /etc/timezone && crond -f -l 8"


volumes:
  pgdata:
  license-server_license_data:
