version: "3.9"

services:
  db:
    image: postgres:16
    container_name: ims_db
    restart: always
    env_file:
      - .env # Use .env file to load environment variables for the backend service
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    container_name: ims_backend
    restart: always
    environment:
      RUNNING_IN_DOCKER: "1"
      LICENSE_MACHINE_ID: ${LICENSE_MACHINE_ID}
    env_file:
      - .env  # Use .env file to load environment variables for the backend service
    depends_on:
      db:
        condition: service_started
    volumes:
      - ./backend/staticfiles:/app/staticfiles
      - ./backend/license.lic:/app/license.lic
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: ims_frontend
    restart: always
    env_file:
      - .env  # Use .env file to load environment variables for the backend service
    depends_on:
      - backend
    ports:
      - "3000:3000"

  backup:
    image: postgres:16-alpine
    container_name: ims_backup
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Kolkata
    volumes:
      - ./backups:/backups
      - ./backup/backup.sh:/backup.sh
      - ./backup/crontabs:/etc/crontabs
    entrypoint: /bin/sh
    command: -c "apk add --no-cache postgresql-client tzdata && cp /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && echo 'Asia/Kolkata' > /etc/timezone && crond -f -l 8"


volumes:
  pgdata:
