version: "3.9"

services:
  db:
    image: postgres:16
    container_name: ims_db
    restart: always
    env_file:
      - .env # Use .env file to load environment variables for the backend service
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  license-server:
    build: ./license-server
    container_name: ims-license-server
    restart: unless-stopped
    ports:
      - "5050:5000"
    volumes:
      - license-server_license_data:/app/data

  backend:
    build: ./backend
    container_name: ims_backend
    hostname: ims-backend-prod
    restart: always
    env_file:
      - .env  # Use .env file to load environment variables for the backend service
    depends_on:
      - db
      - license-server
    volumes:
      - ./backend/staticfiles:/app/staticfiles
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: ims_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pgdata:
  license-server_license_data:
