version: "3.9"

services:
  license-server:
    build: .
    container_name: ims-license-server
    ports:
      - "5050:5050"
    volumes:
      - license-server_license_data:/app/data
    restart: unless-stopped

volumes:
  license-server_license_data:
